# Coursera IBM Data Science Applied Capstone Week 3 Assignment
Segmenting and Clustering Neighborhoods in Toronto

Step 1 \
Mannually copy table from https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M \
into an excel (xlsx) file and upload to IBM cloud and create download link

In [5]:
import numpy as np  # useful for many scientific computing in Python
import pandas as pd # primary data structure library

In [6]:
df = pd.read_excel('https://torontocapstone.s3.jp-tok.cloud-object-storage.appdomain.cloud/Toronto%20neighbourhoods.xlsx',
                       sheet_name='Sheet1',
                       skiprows=range(0),
                       skipfooter=0
                      )

print('Data downloaded and read into a dataframe!')

Data downloaded and read into a dataframe!

In [7]:
df.head(20)

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
7,M8A,Not assigned,Not assigned
8,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
9,M1B,Scarborough,"Malvern, Rouge"
10,M2B,Not assigned,Not assigned
11,M3B,North York,Don Mills
12,M4B,East York,"Parkview Hill, Woodbine Gardens"
13,M5B,Downtown Toronto,"Garden District, Ryerson"
14,M6B,North York,Glencairn
15,M7B,Not assigned,Not assigned
16,M8B,Not assigned,Not assigned
17,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."
18,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
19,M2C,Not assigned,Not assigned

Step 2 \
Remove 'Not assigned' rows and reset index

In [8]:
df.drop(df[df['Borough'] == 'Not assigned'].index, axis = 0, inplace = True)
df.drop(df[df['Neighbourhood'] == 'Not assigned'].index, axis = 0, inplace = True)

In [9]:
df.rename(columns={'Postal Code':'PostalCode'},inplace=True)
df.reset_index(drop=True).head(20)

,PostalCode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
5,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
6,M1B,Scarborough,"Malvern, Rouge"
7,M3B,North York,Don Mills
8,M4B,East York,"Parkview Hill, Woodbine Gardens"
9,M5B,Downtown Toronto,"Garden District, Ryerson"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."
12,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
13,M3C,North York,Don Mills
14,M4C,East York,Woodbine Heights
15,M5C,Downtown Toronto,St. James Town
16,M6C,York,Humewood-Cedarvale
17,M9C,Etobicoke,"Eringate, Bloordale Gardens, Old Burnhamthorpe..."
18,M1E,Scarborough,"Guildwood, Morningside, West Hill"
19,M4E,East Toronto,The Beaches

In [8]:
df.shape

(103, 3)

Step 3 \
Download the csv file with the Latitudes and Longitudes dataset

In [3]:
df_geo = pd.read_csv('http://cocl.us/Geospatial_data')
df_geo.head(20)

   Postal Code   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
5          M1J  43.744734 -79.239476
6          M1K  43.727929 -79.262029
7          M1L  43.711112 -79.284577
8          M1M  43.716316 -79.239476
9          M1N  43.692657 -79.264848
10         M1P  43.757410 -79.273304
11         M1R  43.750072 -79.295849
12         M1S  43.794200 -79.262029
13         M1T  43.781638 -79.304302
14         M1V  43.815252 -79.284577
15         M1W  43.799525 -79.318389
16         M1X  43.836125 -79.205636
17         M2H  43.803762 -79.363452
18         M2J  43.778517 -79.346556
19         M2K  43.786947 -79.385975